### ISSUE TITLE
[Feature Request] Simplify Installation by Reducing Build Dependencies in [build-system]

### ISSUE THREAD

**Issue by Triang-jyed-driung** [fla-org/flash-linear-attention#283]
### Feature Request

Currently, the `pyproject.toml` file includes `torch` as a build dependency under `[build-system]`. Run `pip install -e .` and `pip` attempts to reinstall `torch` (and its dependencies) unnecessarily. This behavior can significantly slow down the installation process.

```toml
[build-system]
requires = ["setuptools>=45", "wheel", "ninja", "torch"]
```

### Motivation

Installation of the project can take an unexpectedly long time on certain systems. Upon closer inspection using the `--verbose` flag, I found that `pip` is attempting to reinstall specific versions of `torch` (e.g., `2.6.0+cu124`) and its associated dependencies.

### Your Contribution

I suggest 2 ways:

1. Remove this
```toml
[build-system]
requires = ["setuptools>=45", "wheel", "ninja", "torch"]
```
(Do we really need it?)

2. Add some hints like `pip install -e . --no-build-isolation` in `README.md`
